### ISSUE TITLE
Compiler - maybe?

### ISSUE THREAD

**Issue by methodbox** [historicalsource/hitchhikersguide#1]
I read about this on Arstechnica, and wanted to let you know that someone there posted a link to a couple of Infocom compilers.

I'll provide the link with a simple warning that I'm not familiar enough with ASCII to know if this works or if it's safe, but I thought I'd pass this along as your README states the compiler is not available.

http://www.ifarchive.org/indexes/if-archiveXinfocomXcompilers.html

**Comment by go2tom42** [comment]
I compiled it with [zilf](http://www.ifarchive.org/indexes/if-archiveXinfocomXcompilersXzilf.html), it seems to play with no issues
Ran following at cmd
`zilf s4.zil` (this created s4.zap)
`zapf s4.zap` (this created s4.z3)
s4.z3 seems run fine in [parchment ](https://github.com/curiousdannii/parchment)(I stopped after taking the aspirin)

**Comment by Kirillism** [comment]
That's amazing! Thank you both!

**Comment by methodbox** [comment]
No problem! Hopefully people who missed out on the old text game days get to appreciate this, and maybe some Zork, too!
