### ISSUE TITLE
How to compile to a .EXE?

### ISSUE THREAD

**Issue by nelgin** [historicalsource/hitchhikersguide#2]
Is there any way I can compile this, I guess I need a ZIL interpreter? Anyway, compile into a single .EXE binary? It looks like the original came with a .EXE and a .DAT file, which would also work.

**Comment by michaelbub** [comment]
The .exe is the interpreter the .dat is the compiled/s4.z3. 
IIRC it's always been like that: interpreter + gamefile, never both rolled into one single .exe.

**Comment by historicalsource** [comment]
Answered correctly - this compiles into z-files, not .exe.
